### ISSUE TITLE
License header missing

### ISSUE THREAD

**Issue by manolodd** [RISCOSS/riscoss-wiki-ui#2]
Most files in this repo have not license specification or license header. They should specify ASL2 in every file or in a license.txt file

**Comment by cjdelisle** [comment]
How about we go with a file called `LICENSE` since we have many many trivially small files?

**Comment by manolodd** [comment]
Caleb, I already suggested this in the issue description :-).

I always prefer the license header in each file (the way the license's authors specify as the valid method  to apply the license), but it is a matter of preferences.

**Comment by cjdelisle** [comment]
fixed in the github-implementation branch, this will be merged back into master soon.
