### ISSUE TITLE
GitHub Analyzer version 2 deployment

### ISSUE THREAD

**Issue by slauriere** [RISCOSS/riscoss-wiki-ui#26]
A second version of the [GitHub Analyzer](https://github.com/RISCOSS/riscoss-wiki-ui/tree/github-implementation) app is being developed by the XWiki Labs team. It's about to be ready for deployment on  the [Riscoss GitHub Analyzer domain](http://riscossplatform.ow2.org/riscoss/wiki/githubanalyser/).

Main new features:
- bugfix
- view all your GitHub projects directly from the app
- launch analysis directly from the projects table

**Comment by cjdelisle** [comment]
Planned for Thursday sept 3

**Comment by cjdelisle** [comment]
Blockers are #28 #41 #51 #54

**Comment by cjdelisle** [comment]
released yesterday on domain 'gha'
