### ISSUE TITLE
Issue when evaluating component for use case

### ISSUE THREAD

**Issue by mouhb** [RISCOSS/riscoss-wiki-ui#4]
![unnamed](https://cloud.githubusercontent.com/assets/3015046/6865445/273ae58a-d46e-11e4-9243-c53253a4dc90.png)

**Comment by cjdelisle** [comment]
This would be more useful with the content of the RAWOUT (which goes off the screen)

**Comment by cjdelisle** [comment]
Looks like a dupe of https://github.com/RISCOSS/riscoss-platform-core/issues/19
