### ISSUE TITLE
Issue when creating a new risk analysis session

### ISSUE THREAD

**Issue by mouhb** [RISCOSS/riscoss-wiki-ui#5]
The issue below apears when I try to perform the evaluation

![issue](https://cloud.githubusercontent.com/assets/3015046/6865762/9a2fbe78-d471-11e4-9732-14335beb1a3f.png)

**Comment by cjdelisle** [comment]
Ok, the development server is a bit out of date, as soon as we have it up to the current status we can re-test this.
