### ISSUE TITLE
Running an analysis over an existing one fails without notice

### ISSUE THREAD

**Issue by slauriere** [RISCOSS/riscoss-wiki-ui#52]
It seems that when a project was not properly deleted (eg some analysis pages remain existing in the wiki), a new project analysis will fail without notice. We may consider overwriting existing analysis in this case and output some result. (see the case of https://github.com/manolodd/opensimmpls for instance)

**Comment by cjdelisle** [comment]
This should be fixed in v2 of the github instance. Feel free to reopen if it persists after deployment.
