### ISSUE TITLE
User Feedback and Expert Feedback links remove ~ character

### ISSUE THREAD

**Issue by cjdelisle** [RISCOSS/riscoss-wiki-ui#8]
the ~ char is an escape char in xwiki so this is not surprising, the solution is to use HTML/wiki=false and then an <a> tag

**Comment by lidix91** [comment]
Current deployment is not using the URL containing  ~ char, it this issue fixed or this kind of URLs cannot be used?

**Comment by slauriere** [comment]
As far I can see on the [app site](http://riscossplatform.ow2.org/riscoss/wiki/githubanalyser/), the links to the forms are now working as expected, aren't they? Can we close the issue?

**Comment by lidix91** [comment]
For me, yes
